DROP TABLE IF EXISTS images;

CREATE TABLE images (
  id INT PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(512) UNIQUE NOT NULL,
  views INT NOT NULL DEFAULT 0,
  likes INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);